name: 'External Telegram Notificatios'
description: 'Configure an endpoint to get the content to send to a telegram chat'
inputs:
  token:
    description: 'Token of the telegram bot'
      required: true
  to:
    description: 'Id of the telegram chat or channel'
      required: true
  content-url:
    description: 'Url with the content to send to telegram'
      required: true
outputs:
  time: # id of output
    description: 'The time we we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
